### ISSUE TITLE
Issue de TESTE

### ISSUE THREAD

**Issue by arraisgabriel** [tramaLabs/Conteudo#12]

**Comment by nevescode** [comment]
legal

**Comment by nevescode** [comment]
cabou

**Comment by arraisgabriel** [comment]
Issue encerrada pq os testes acabaram. Ê!

**Comment by ribeirofelix** [comment]
nao terminou, tem coisa pra fazer LOL

**Comment by nevescode** [comment]
😱😱😱😱😱

**Comment by kbooz** [comment]
Mas gente 🔝 🔝 🔝

**Comment by ribeirofelix** [comment]
Eu não sou *colaborador* do repositório, eu não posso REABRIR a issue! 
@arraisgabriel pode reabrir _PORFA_?!

**Comment by ribeirofelix** [comment]
Obrigado @nevescode !

**Comment by gabrielaornellas2** [comment]
Chega galera

**Comment by gabrielaornellas2** [comment]
"Vai ficar pra posterioridade"

**Comment by gabrielaornellas2** [comment]
-neves
